Add example using lifted-base/bracket for resource handling (#356)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,19 +4,20 @@
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.3
+# version: 0.8
 #
+version: ~> 1.0
 language: c
+os: linux
 dist: xenial
-
 git:
-  submodules: false  # whether to recursively clone submodules
-
+  # whether to recursively clone submodules
+  submodules: false
 cache:
   directories:
     - $HOME/.cabal/packages
     - $HOME/.cabal/store
-
+    - $HOME/.hlint
 before_cache:
   - rm -fv $CABALHOME/packages/hackage.haskell.org/build-reports.log
   # remove files that are regenerated by 'cabal update'
@@ -25,54 +26,118 @@ before_cache:
   - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.cache
   - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar
   - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar.idx
-
   - rm -rfv $CABALHOME/packages/head.hackage
-
-matrix:
+jobs:
   include:
-    # check the oldest versions first as they're most likely to fail.
-    - compiler: "ghc-8.0.2"
-      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.0.2], sources: [hvr-ghc]}}
-    - compiler: "ghc-8.2.2"
-      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
-    - compiler: "ghc-8.4.4"
-      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.4.4], sources: [hvr-ghc]}}
-    - compiler: "ghc-8.6.5"
-      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.6.5], sources: [hvr-ghc]}}
-    - compiler: "ghc-8.8.1"
-      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-3.0,ghc-8.8.1], sources: [hvr-ghc]}}
-
+    - compiler: ghc-8.8.1
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.8.1","cabal-install-3.0"]}}
+      os: linux
+    - compiler: ghc-8.6.5
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.6.5","cabal-install-3.0"]}}
+      os: linux
+    - compiler: ghc-8.4.4
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.4.4","cabal-install-3.0"]}}
+      os: linux
+    - compiler: ghc-8.2.2
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.2.2","cabal-install-3.0"]}}
+      os: linux
+    - compiler: ghc-8.0.2
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.0.2","cabal-install-3.0"]}}
+      os: linux
 before_install:
-  - HC=/opt/ghc/bin/${CC}
-  - HCPKG=${HC/ghc/ghc-pkg}
+  - HC=$(echo "/opt/$CC/bin/ghc" | sed 's/-/\//')
+  - WITHCOMPILER="-w $HC"
+  - HADDOCK=$(echo "/opt/$CC/bin/haddock" | sed 's/-/\//')
+  - HCPKG="$HC-pkg"
   - unset CC
   - CABAL=/opt/ghc/bin/cabal
   - CABALHOME=$HOME/.cabal
   - export PATH="$CABALHOME/bin:$PATH"
-  - ROOTDIR=$(pwd)
-  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+  - TOP=$(pwd)
+  - "HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\\d+)\\.(\\d+)\\.(\\d+)(\\.(\\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')"
   - echo $HCNUMVER
-
+  - CABAL="$CABAL -vnormal+nowrap+markoutput"
+  - set -o pipefail
+  - |
+    echo 'function blue(s) { printf "\033[0;34m" s "\033[0m " }'           >> .colorful.awk
+    echo 'BEGIN { state = "output"; }'                                     >> .colorful.awk
+    echo '/^-----BEGIN CABAL OUTPUT-----$/ { state = "cabal" }'            >> .colorful.awk
+    echo '/^-----END CABAL OUTPUT-----$/ { state = "output" }'             >> .colorful.awk
+    echo '!/^(-----BEGIN CABAL OUTPUT-----|-----END CABAL OUTPUT-----)/ {' >> .colorful.awk
+    echo '  if (state == "cabal") {'                                       >> .colorful.awk
+    echo '    print blue($0)'                                              >> .colorful.awk
+    echo '  } else {'                                                      >> .colorful.awk
+    echo '    print $0'                                                    >> .colorful.awk
+    echo '  }'                                                             >> .colorful.awk
+    echo '}'                                                               >> .colorful.awk
+  - cat .colorful.awk
+  - |
+    color_cabal_output () {
+      awk -f $TOP/.colorful.awk
+    }
+  - echo text | color_cabal_output
 install:
   - ${CABAL} --version
   - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
   - TEST=--enable-tests
   - BENCH=--enable-benchmarks
-  - GHCHEAD=${GHCHEAD-false}
-  - travis_retry ${CABAL} update -v
-  - sed -i.bak 's/^jobs:/-- jobs:/' $CABALHOME/config
-  - rm -fv cabal.project cabal.project.local
-  - grep -Ev -- '^\s*--' $CABALHOME/config | grep -Ev '^\s*$'
-  - rm -f cabal.project
+  - HEADHACKAGE=false
+  - rm -f $CABALHOME/config
+  - |
+    echo "verbose: normal +nowrap +markoutput"                                  >> $CABALHOME/config
+    echo "remote-build-reporting: anonymous"                                    >> $CABALHOME/config
+    echo "write-ghc-environment-files: always"                                  >> $CABALHOME/config
+    echo "remote-repo-cache: $CABALHOME/packages"                               >> $CABALHOME/config
+    echo "logs-dir:          $CABALHOME/logs"                                   >> $CABALHOME/config
+    echo "world-file:        $CABALHOME/world"                                  >> $CABALHOME/config
+    echo "extra-prog-path:   $CABALHOME/bin"                                    >> $CABALHOME/config
+    echo "symlink-bindir:    $CABALHOME/bin"                                    >> $CABALHOME/config
+    echo "installdir:        $CABALHOME/bin"                                    >> $CABALHOME/config
+    echo "build-summary:     $CABALHOME/logs/build.log"                         >> $CABALHOME/config
+    echo "store-dir:         $CABALHOME/store"                                  >> $CABALHOME/config
+    echo "install-dirs user"                                                    >> $CABALHOME/config
+    echo "  prefix: $CABALHOME"                                                 >> $CABALHOME/config
+    echo "repository hackage.haskell.org"                                       >> $CABALHOME/config
+    echo "  url: http://hackage.haskell.org/"                                   >> $CABALHOME/config
+    echo "  secure: True"                                                       >> $CABALHOME/config
+    echo "  key-threshold: 3"                                                   >> $CABALHOME/config
+    echo "  root-keys:"                                                         >> $CABALHOME/config
+    echo "    fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0" >> $CABALHOME/config
+    echo "    1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42" >> $CABALHOME/config
+    echo "    2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3" >> $CABALHOME/config
+    echo "    0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d" >> $CABALHOME/config
+    echo "    51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921" >> $CABALHOME/config
+  - |
+    echo "program-default-options"                >> $CABALHOME/config
+    echo "  ghc-options: $GHCJOBS +RTS -M6G -RTS" >> $CABALHOME/config
+  - cat $CABALHOME/config
+  - rm -fv cabal.project cabal.project.local cabal.project.freeze
+  - travis_retry ${CABAL} v2-update -v
+  # Generate cabal.project
+  - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
-  - "printf 'packages: \"hedgehog\"\\n' >> cabal.project"
-  - "printf 'packages: \"hedgehog-dieharder\"\\n' >> cabal.project"
-  - "printf 'packages: \"hedgehog-example\"\\n' >> cabal.project"
-  - "printf 'packages: \"hedgehog-quickcheck\"\\n' >> cabal.project"
-  - "printf 'packages: \"hedgehog-test-laws\"\\n' >> cabal.project"
-  - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
-  - touch cabal.project.local
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | grep -vE -- '^(hedgehog|hedgehog-dieharder|hedgehog-example|hedgehog-quickcheck|hedgehog-test-laws)$' | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - |
+    echo "packages: hedgehog" >> cabal.project
+    echo "packages: hedgehog-dieharder" >> cabal.project
+    echo "packages: hedgehog-example" >> cabal.project
+    echo "packages: hedgehog-quickcheck" >> cabal.project
+    echo "packages: hedgehog-test-laws" >> cabal.project
+  - |
+    echo "package hedgehog"             >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+    echo ""                             >> cabal.project
+    echo "package hedgehog-dieharder"   >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+    echo ""                             >> cabal.project
+    echo "package hedgehog-example"     >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+    echo ""                             >> cabal.project
+    echo "package hedgehog-quickcheck"  >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+    echo ""                             >> cabal.project
+    echo "package hedgehog-test-laws"   >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(hedgehog|hedgehog-dieharder|hedgehog-example|hedgehog-quickcheck|hedgehog-test-laws)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   - if [ -f "hedgehog/configure.ac" ]; then (cd "hedgehog" && autoreconf -i); fi
@@ -80,54 +145,71 @@ install:
   - if [ -f "hedgehog-example/configure.ac" ]; then (cd "hedgehog-example" && autoreconf -i); fi
   - if [ -f "hedgehog-quickcheck/configure.ac" ]; then (cd "hedgehog-quickcheck" && autoreconf -i); fi
   - if [ -f "hedgehog-test-laws/configure.ac" ]; then (cd "hedgehog-test-laws" && autoreconf -i); fi
-  - rm -f cabal.project.freeze
-  - ${CABAL} new-freeze -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dry
-  - "cat \"cabal.project.freeze\" | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
-  - rm  "cabal.project.freeze"
-  - ${CABAL} new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
-  - ${CABAL} new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
-  - rm -rf .ghc.environment.* "hedgehog"/dist "hedgehog-dieharder"/dist "hedgehog-example"/dist "hedgehog-quickcheck"/dist "hedgehog-test-laws"/dist
-  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
-
-# Here starts the actual work to be performed for the package under test;
-# any command which exits with a non-zero exit code causes the build to fail.
+  - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH} | color_cabal_output
+  - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
+  - rm  cabal.project.freeze
+  - ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} --dep -j2 all | color_cabal_output
+  - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks --dep -j2 all | color_cabal_output
 script:
-  # test that source-distributions can be generated
-  - ${CABAL} new-sdist all
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
+  # Packaging...
+  - ${CABAL} v2-sdist all | color_cabal_output
+  # Unpacking...
   - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
   - cd ${DISTDIR} || false
-  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
-  - rm -f cabal.project
+  - find . -maxdepth 1 -type f -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - find . -maxdepth 1 -type f -name '*.tar.gz' -exec rm       '{}' \;
+  - PKGDIR_hedgehog="$(find . -maxdepth 1 -type d -regex '.*/hedgehog-[0-9.]*')"
+  - PKGDIR_hedgehog_dieharder="$(find . -maxdepth 1 -type d -regex '.*/hedgehog-dieharder-[0-9.]*')"
+  - PKGDIR_hedgehog_example="$(find . -maxdepth 1 -type d -regex '.*/hedgehog-example-[0-9.]*')"
+  - PKGDIR_hedgehog_quickcheck="$(find . -maxdepth 1 -type d -regex '.*/hedgehog-quickcheck-[0-9.]*')"
+  - PKGDIR_hedgehog_test_laws="$(find . -maxdepth 1 -type d -regex '.*/hedgehog-test-laws-[0-9.]*')"
+  # Generate cabal.project
+  - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
-  - "printf 'packages: \"hedgehog-*/*.cabal\"\\n' >> cabal.project"
-  - "printf 'packages: \"hedgehog-dieharder-*/*.cabal\"\\n' >> cabal.project"
-  - "printf 'packages: \"hedgehog-example-*/*.cabal\"\\n' >> cabal.project"
-  - "printf 'packages: \"hedgehog-quickcheck-*/*.cabal\"\\n' >> cabal.project"
-  - "printf 'packages: \"hedgehog-test-laws-*/*.cabal\"\\n' >> cabal.project"
-  - "printf 'write-ghc-environment-files: always\\n' >> cabal.project"
-  - touch cabal.project.local
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | grep -vE -- '^(hedgehog|hedgehog-dieharder|hedgehog-example|hedgehog-quickcheck|hedgehog-test-laws)$' | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - |
+    echo "packages: ${PKGDIR_hedgehog}" >> cabal.project
+    echo "packages: ${PKGDIR_hedgehog_dieharder}" >> cabal.project
+    echo "packages: ${PKGDIR_hedgehog_example}" >> cabal.project
+    echo "packages: ${PKGDIR_hedgehog_quickcheck}" >> cabal.project
+    echo "packages: ${PKGDIR_hedgehog_test_laws}" >> cabal.project
+  - |
+    echo "package hedgehog"             >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+    echo ""                             >> cabal.project
+    echo "package hedgehog-dieharder"   >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+    echo ""                             >> cabal.project
+    echo "package hedgehog-example"     >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+    echo ""                             >> cabal.project
+    echo "package hedgehog-quickcheck"  >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+    echo ""                             >> cabal.project
+    echo "package hedgehog-test-laws"   >> cabal.project
+    echo "  ghc-options: -Wall -Werror" >> cabal.project
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(hedgehog|hedgehog-dieharder|hedgehog-example|hedgehog-quickcheck|hedgehog-test-laws)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
+  # Building...
   # this builds all libraries and executables (without tests/benchmarks)
-  - ${CABAL} new-build -w ${HC} --disable-tests --disable-benchmarks all
-
+  - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks all | color_cabal_output
+  # Building with tests and benchmarks...
   # build & run tests, build benchmarks
-  - ${CABAL} new-build -w ${HC} ${TEST} ${BENCH} all
-  - ${CABAL} new-test -w ${HC} ${TEST} ${BENCH} all
+  - ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} all | color_cabal_output
+  # Testing...
+  - ${CABAL} v2-test $WITHCOMPILER ${TEST} ${BENCH} all | color_cabal_output
+  # cabal check...
+  - (cd ${PKGDIR_hedgehog} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_hedgehog_dieharder} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_hedgehog_example} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_hedgehog_quickcheck} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_hedgehog_test_laws} && ${CABAL} -vnormal check)
+  # haddock...
+  - ${CABAL} v2-haddock $WITHCOMPILER --with-haddock $HADDOCK ${TEST} ${BENCH} all | color_cabal_output
+  # Building without installed constraints for packages in global-db...
+  - rm -f cabal.project.local
+  - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks all | color_cabal_output
 
-  # cabal check
-  - (cd hedgehog-* && ${CABAL} check)
-  - (cd hedgehog-dieharder-* && ${CABAL} check)
-  - (cd hedgehog-example-* && ${CABAL} check)
-  - (cd hedgehog-quickcheck-* && ${CABAL} check)
-  - (cd hedgehog-test-laws-* && ${CABAL} check)
-
-  # haddock
-  - ${CABAL} new-haddock -w ${HC} ${TEST} ${BENCH} all
-
-  # Build without installed constraints for packages in global-db
-  - rm -f cabal.project.local; ${CABAL} new-build -w ${HC} --disable-tests --disable-benchmarks all
-
-# REGENDATA ["cabal.project"]
+# REGENDATA ("0.8",["cabal.project"])
 # EOF
